name: ci

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 270
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

#      - name: Update system packages
#        run: |
#          sudo apt-get update
#          sudo apt-get dist-upgrade -y
#          sudo apt-get clean
#          sudo apt-get autoremove -y

      - name: Set up Git credentials
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone and organize bot repository
        run: |
          git clone -b tgenc-1 https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} ${{ secrets.GIT_NAME }}
          cd ${{ secrets.GIT_NAME }}
          git clone https://github.com/Nubuki-all/Enc temp_enc_repo
          rm temp_enc_repo/bot/__init__.py
          rm temp_enc_repo/Dockerfile
          mv temp_enc_repo/* .
          rm -rf temp_enc_repo
          curl -o bot/__init__.py https://katb.in/adavujekeji/raw

      - name: Build and run Docker container
        run: |
          cd ${{ secrets.GIT_NAME }}
          docker build . -t tetris
          docker run tetris

      - name: Update loop repository
        run: |
          git clone -b master https://${{ secrets.SUPER_TOKEN }}@github.com/${{ github.repository }} loop
          cd loop || exit 1
          echo $(( RANDOM - (RANDOM % RANDOM) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow: Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${{ github.repository }} HEAD:master